### ISSUE TITLE
npm, npx, and yarn scripts are throwing an error — Cannot find module '../dist/lib'

### ISSUE THREAD

**Issue by wcalderipe** [filipesilva/create-cljs-app#185]
Hey folks :wave: 

I'm having an error with `npm`, `npx` and `yarn` following the same instructions described on the README.

OS: `Ubuntu 20.04.1 LTS`
OpenJDK:  `build 11.0.8+10-post-Ubuntu-0ubuntu120.04`

-----

Using `npm` and `npx`.

```
~/dev❯ npm -v
6.14.4
~/dev❯ npm init cljs-app my-app

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../dist/lib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/wcalderipe/.config/yarn/global/node_modules/create-cljs-app/bin/create-cljs-app.js:3:20)
                                                     /\ NOTICE THIS.

    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
~/dev❯ npx create-cljs-app my-app
Cannot find module '../dist/lib'
```
I also noticed that npm is trying to reach out yarn packages and I don't if this was intended. 

-----

Using `yarn`.

```
~/dev❯ yarn -v
1.22.5
~/dev❯ yarn create cljs-app my-app
yarn create v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "create-cljs-app@0.4.1" with binaries:
      - create-cljs-app
[########################################] 40/40internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../dist/lib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/wcalderipe/.config/yarn/global/node_modules/create-cljs-app/bin/create-cljs-app.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed.
Exit code: 1
Command: /home/wcalderipe/.local/npm/bin/create-cljs-app
Arguments: my-app
Directory: /home/wcalderipe/dev
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```
----- 

**Note:** I don't know if this might impact the template scripts but I have changed the npm prefix to a different folder under my user so I don't have to install global packages using `sudo`.

**Comment by filipesilva** [comment]
Ok, should be fixed now in 0.4.3. Turns I was using a master ref for the github upload/download actions and their behaviour changed a bit. Pinned them now.

**Comment by wcalderipe** [comment]
@filipesilva thanks for the fast replies for keeping the issue updated. 

I'll give it another whirl tomorrow. Looking forward to seeing how you folks are using devcards with shadow-cljs.

**Comment by filipesilva** [comment]
@wcalderipe still on an older version of React and Devcards, I'm afraid. 

It's possible to update but a little hairy, see https://github.com/bhauman/devcards/issues/168.
